[build]
  Command = "npm run build"
  Functions = "lambda"
  Publish = "public"

[[redirects]]
  from = "/"
  to = "/app/home"

[template.environment]
  FAUNADB_CINEDIM_SECRET = "Your FaunaDB Server Secret"
